name: Add directory

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir nieuwe_map
      - run: echo dit is een stuk tekst > nieuwe_map/nieuwe_tekst
      - run: cat nieuwe_tekst/nieuwe_tekst
    
