name: New issue

on:
  issues:
    types: [opened]
jobs:
  log-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Toon titel en body van het issue
      - run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body:"
          echo "${{ github.event.issue.body }}"
    
  
