name: Uses Examples
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Setup python v3.13
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
      - name: Run my_script.py
      - run: python my_script.py
      
          
